default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  username: root
  port: 3306
  host: db
  database: myapp_development
  password: password

test:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  username: root
  port: 3306
  host: db
  database: myapp_test
  password: password

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
