name: Wake Up Render Apps

on:
  schedule:
    - cron: "*/12 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.4" # ここでRubyバージョンを指定
          bundler-cache: true # Gemfile.lockに基づいてgemをキャッシュ
      - name: Install dependencies
        run: bundle install
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend App
        run: |
          # RenderバックエンドアプリケーションのURLにGETリクエストを送信
          curl -f -s ${{ secrets.RENDER_BACKEND_APP_URL }} > /dev/null || { echo "Backend Ping failed!"; exit 1; }
          echo "Render backend app pinged successfully!"
      - name: Ping Render Frontend App
        run: |
          # RenderフロントエンドアプリケーションのURLにGETリクエストを送信
          curl -f -s ${{ secrets.RENDER_FRONTEND_APP_URL }} > /dev/null || { echo "Frontend Ping failed!"; exit 1; }
          echo "Render frontend app pinged successfully!"
