name: Wake Up Render Apps

on:
  schedule:
    - cron: "*/12 * * * *"

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend App
        run: |
          if [ -z "${{ secrets.RENDER_BACKEND_APP_URL }}" ]; then
            echo "RENDER_BACKEND_APP_URL secret is not set"
            exit 1
          fi
          echo "Pinging backend: ${{ secrets.RENDER_BACKEND_APP_URL }}"
          curl -f -s --max-time 30 "${{ secrets.RENDER_BACKEND_APP_URL }}" > /dev/null
          echo "Backend ping successful!"
        continue-on-error: true

      - name: Ping Render Frontend App
        run: |
          if [ -z "${{ secrets.RENDER_FRONTEND_APP_URL }}" ]; then
            echo "RENDER_FRONTEND_APP_URL secret is not set"
            exit 1
          fi
          echo "Pinging frontend: ${{ secrets.RENDER_FRONTEND_APP_URL }}"
          curl -f -s --max-time 30 "${{ secrets.RENDER_FRONTEND_APP_URL }}" > /dev/null
          echo "Frontend ping successful!"
        continue-on-error: true
